name: RideOn
version: 2.0
description: RideOn
author: kubotan
website: http://about.gorogoro.space/

main: space.gorogoro.rideon.RideOn

commands:
  rideon:
    usage: /<command> 肩車機能をON/OFFします。
  rideondeny:
    usage: /<command> <playername> 指定したプレイヤーを肩車拒否します。
    